"""
GitHub Publisher Tool - Fixed Version
Location: src/tools/github_publisher.py
"""

from github import Github, Auth, GithubException
import os
from datetime import datetime
from dotenv import load_dotenv

class GitHubPublisher:
    def __init__(self, token=None, repo_owner=None, repo_name=None):
        """Initialize GitHub publisher with proper authentication"""
        load_dotenv()
        
        self.token = token or os.getenv('GITHUB_TOKEN')
        if not self.token:
            raise ValueError("GitHub token not found!")
        
        # Use modern authentication (fixes 404 error)
        auth = Auth.Token(self.token)
        self.github = Github(auth=auth)
        
        # Configuration
        self.repo_owner = repo_owner or "AhsenMahmood"
        self.repo_name = repo_name or "nist-compliance-sentinel"
        self.base_branch = "main"
        
    def publish_summary(self, summary_content, filename=None):
        """
        Publish NIST summary to GitHub via Pull Request
        
        Args:
            summary_content (str): The markdown content to publish
            filename (str): Optional custom filename
            
        Returns:
            dict: Result with PR URL or error details
        """
        try:
            # Get repository
            repo = self.github.get_repo(f"{self.repo_owner}/{self.repo_name}")
            print(f"Connected to repo: {repo.full_name}")
            
            # Generate filename if not provided
            if not filename:
                timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
                filename = f"nist-summary-{timestamp}.md"
            
            # Create branch name
            branch_name = f"nist-update-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
            
            # Get base branch reference
            base_ref = repo.get_git_ref(f"heads/{self.base_branch}")
            base_sha = base_ref.object.sha
            
            # Create new branch
            print(f"Creating branch: {branch_name}")
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_sha
            )
            
            # Create or update file
            file_path = f"summaries/{filename}"
            print(f"Creating file: {file_path}")
            
            try:
                # Try to get existing file (in case it exists)
                contents = repo.get_contents(file_path, ref=branch_name)
                repo.update_file(
                    path=file_path,
                    message=f"Update NIST SP 800 Summary - {datetime.now().strftime('%Y-%m-%d')}",
                    content=summary_content,
                    sha=contents.sha,
                    branch=branch_name
                )
            except GithubException as e:
                if e.status == 404:
                    # File doesn't exist, create it
                    repo.create_file(
                        path=file_path,
                        message=f"Add NIST SP 800 Summary - {datetime.now().strftime('%Y-%m-%d')}",
                        content=summary_content,
                        branch=branch_name
                    )
                else:
                    raise
            
            # Create Pull Request
            print(f"Creating Pull Request...")
            pr_title = f"NIST SP 800 Compliance Update - {datetime.now().strftime('%Y-%m-%d')}"
            pr_body = f"""## NIST SP 800 Compliance Update

This PR contains the latest NIST SP 800 series updates relevant to software development.

### Summary
- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **File**: `{file_path}`
- **Source**: Automated NIST Monitoring System

### Automated Report
This update was automatically generated by the NIST Compliance Agent.

---
**Note**: Please review the changes before merging.
"""
            
            pr = repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=self.base_branch
            )
            
            print(f" Pull Request created: {pr.html_url}")
            
            return {
                "success": True,
                "pr_url": pr.html_url,
                "pr_number": pr.number,
                "branch": branch_name,
                "file_path": file_path
            }
            
        except GithubException as e:
            error_msg = f"GitHub API Error: {e.status} {e.data}"
            print(f"{error_msg}")
            return {
                "success": False,
                "error": error_msg,
                "details": str(e)
            }
        except Exception as e:
            error_msg = f"Unexpected error: {str(e)}"
            print(f" {error_msg}")
            return {
                "success": False,
                "error": error_msg
            }
    
    def verify_access(self):
        """Verify GitHub access and repository permissions"""
        try:
            repo = self.github.get_repo(f"{self.repo_owner}/{self.repo_name}")
            user = self.github.get_user()
            
            print(f"GitHub Access Verified")
            print(f"   User: {user.login}")
            print(f"   Repo: {repo.full_name}")
            print(f"   Default branch: {repo.default_branch}")
            
            return True
        except Exception as e:
            print(f"Access verification failed: {e}")
            return False